### ISSUE TITLE
Dateipfade anpassen

### ISSUE THREAD

**Issue by Siimeloni** [Siimeloni/laburinthos#24]
Auf beiden Systemen werden unterschiedliche Dateipfade verwendet. Die Ausgabe soll immer im Assets/ Ordener erfolgen.

**Comment by Monoceros123** [comment]
Das Problem konnte durch die tasks.json Datei und eine Änderung der launch.json Datei behoben werden. Jetzt werden die korrekten relativen Dateipfade, sowohl bei Linux wie bei Windows, verwendet.
